# Generated by Django 4.2.2 on 2023-08-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.TextField(max_length=500)),
                ('timestemp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
