# Generated by Django 4.2.2 on 2023-08-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('last_time', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('salary', models.FloatField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('image', models.FileField(null=True, upload_to='')),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
    ]
