# Generated by Django 4.2.2 on 2023-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
