# Generated by Django 4.2.2 on 2023-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_last_time_alter_job_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
